### ISSUE TITLE
TypeError: OCR.retrieveText is not a function

### ISSUE THREAD

**Issue by SethaVa** [EddyVerbruggen/nativescript-ocr#12]
I have some troubles using ocr with native-script-vue on android:

//================= Code =======================

> <template>
    <Page class="page">
        <ActionBar title="Camera" class="action-bar" />
        <StackLayout>
            <Button text="Show" @tap="_getTranslate" />
        </StackLayout>
    </Page>
</template>

> <script>
    import * as camera from "../nativescript-camera";
    import * as http from "http";
    import * as OCR from "../nativescript-ocr";

    const imageSourceModule = require("tns-core-modules/image-source");
    const fileSystemModule = require("tns-core-modules/file-system");

    export default {
        data() {
            return {
                native_img: "https://upload.wikimedia.org/wikipedia/en/3/33/Hello_world%21.png"
            };
        },
        methods: {
            _getTranslate() {
                OCR.retrieveText({
                    image: this.native_img
                }).then(result => {
                    console.log(`Result: ${result.text}`);
                });
            }
        }
    };
</script>

//============================================

but got this error in console:

> TypeError: OCR.retrieveText is not a function
File: "file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js, line: 45, column: 16

StackTrace: 
Frame: function:'_getTranslate', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 45, column: 17
Frame: function:'invoker', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3816, column: 18
Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
at com.tns.Runtime.callJSMethod(Runtime.java:987)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:17)
at android.view.View.performClick(View.java:6205)
at android.widget.TextView.performClick(TextView.java:11103)
at android.view.View$PerformClick.run(View.java:23653)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by EddyVerbruggen** [comment]
I think you're better off using the ML Kit feature - see the note at the top of the readme.
